# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20170620_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
