# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 723fa7021a4807301f9ef2d33e26201fc8b7259cb9d91058027ded6260eb2119e28026858a28ec5481031551d87f7631d6ec3b94b684897908c40d18b8fbeb22

test:
  secret_key_base: 20b5f62b94010d43df8947b0a0a59495c6ac32d409fbf2e194a505ba38beccbc4314d4f1f5bd95e10bf86deed1f634d0b37383cd96e5261b021a54ada9d31891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
