# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('username_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
