# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b996f2210ab2e3c5ed80c21e22318411e7992c9b598fdc17f25470ba9c1124af3bd0f99002a808cb9fdd41a2e4f2c742275b8e722bc4b742153615e74235bf

test:
  secret_key_base: 1d0d04dc9a0422e2c162ef3ed0eca10c3fcc1c60c8f2cc4316e34e5a9f3a884dca0dba8eb456c563413caeaaa422a5692e215c323f7c824086006d8228e7a850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
